### ISSUE TITLE
Peer to peer code review October 13th

### ISSUE THREAD

**Issue by IngDavidTM** [Miliyonayalew/Leaderboard#3]
# Review Feedback
Generally, you have a good code without errors and a well-arranged layout. JavaScript is organized in modules with no linters error(s). We like the way that you implement User experience in your project.
However, below are some places we think you can improve on 👍 ;
- Kindly you should deploy your project so that anyone can interact with it.
- You should show a message when the user tries to send a form that doesn't have the right patterns or it's empty.
- Also, you should improve your README file, specifically Getting Started and Install.

Happy  Coding 💯

**Comment by Miliyonayalew** [comment]
Thanks my friends, for your valuable feedback.
